<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLt79lCt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLt79lCt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLt79lCt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLt79lCt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLt79lCt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lt79lCt',
    'container.build_id' => 'fd57c7ad',
    'container.build_time' => 1670418694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLt79lCt');
