<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP8hNxFP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP8hNxFP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP8hNxFP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP8hNxFP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP8hNxFP\App_KernelDevDebugContainer([
    'container.build_hash' => 'P8hNxFP',
    'container.build_id' => 'c9eb4c1e',
    'container.build_time' => 1670342464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP8hNxFP');
